//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARideShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RideCordinate
    {
        public int ride_id { get; set; }
        public int cord_id { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
    
        public virtual Ride Ride { get; set; }
    }
}
