//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARideShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiderInfo
    {
        public int ride_id { get; set; }
        public int user_id { get; set; }
        public string start_location { get; set; }
        public string end_location { get; set; }
        public Nullable<System.TimeSpan> pickup_time { get; set; }
        public string comments { get; set; }
        public Nullable<decimal> rating { get; set; }
        public Nullable<decimal> start_latitude { get; set; }
        public Nullable<decimal> start_longitude { get; set; }
        public Nullable<decimal> end_latitude { get; set; }
        public Nullable<decimal> end_longitude { get; set; }
        public string status { get; set; }
    
        public virtual Ride Ride { get; set; }
        public virtual User User { get; set; }
    }
}
