//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARideShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Rides = new HashSet<Ride>();
            this.RiderInfoes = new HashSet<RiderInfo>();
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string location { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public string telephone { get; set; }
        public string token { get; set; }
        public Nullable<decimal> rating { get; set; }
    
        public virtual ICollection<Ride> Rides { get; set; }
        public virtual ICollection<RiderInfo> RiderInfoes { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
